### ISSUE TITLE
Question: ndefined: syscall.SIGUSR1 undefined: syscall.Rlimit undefined: syscall.Getrlimit undefined: syscall.RLIMIT_NOFILE

### ISSUE THREAD

**Issue by sevtin** [vitessio/vitess#14893]
### Question

GOOS=windows GOARCH=amd64 go build

# vitess.io/vitess/go/vt/servenv
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/pprof.go:312:39: undefined: syscall.SIGUSR1
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/pprof.go:315:38: undefined: syscall.SIGUSR1
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/pprof.go:322:26: undefined: syscall.SIGUSR1
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/pprof.go:323:39: undefined: syscall.SIGUSR1
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/pprof.go:331:26: undefined: syscall.SIGUSR1
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/pprof.go:332:40: undefined: syscall.SIGUSR1
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/servenv.go:156:22: undefined: syscall.Rlimit
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/servenv.go:157:20: undefined: syscall.Getrlimit
/Users/lark/go/pkg/mod/vitess.io/vitess@v0.18.2/go/vt/servenv/servenv.go:157:38: undefined: syscall.RLIMIT_NOFILE

**Comment by mattlord** [comment]
Hi @sevtin,

What was the question? Vitess did/does not have any explicit support for Windows. BUT, I believe that it will at least compile on `main` (19.0.0-SNAPSHOT, with the 19.0-RC release target date being February 6) now after: https://github.com/vitessio/vitess/pull/14718

I'm going to close this for now as I don't see any question to answer.

Best Regards
